spring:
  application:
    name: api-cadastro-usuarios
  

  profiles:
    active: dev
  
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true


server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
  error:
    include-stacktrace: never
    include-message: always


logging:
  level:
    root: INFO
    com.businessbrasil.api: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-cadastro-usuarios.log


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true


spring.validation:
  enabled: true


app:
  name: "API Cadastro de Usuários"
  version: "1.0.0"
  description: "API REST para cadastro de usuários - Desafio Técnico Grupo Business Brasil"
  contact:
    name: "Alex Caje Felix"
    email: "alex@businessbrasil.com"
  company:
    name: "Grupo Business Brasil"
    email: "rh@grupobusinessbrasil.com.br"
