spring:
  config:
    activate:
      on-profile: prod
  
 
  datasource:
    url: jdbc:h2:file:./data/proddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false


logging:
  level:
    root: WARN
    com.businessbrasil.api: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/api-cadastro-usuarios-prod.log

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: always
