services:
  api:
    build: .
    container_name: api-cadastro-usuarios
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - api-network
    restart: unless-stopped

networks:
  api-network:
    driver: bridge